/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default Methods</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.DefaultMethods#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.DefaultMethods#getAnything <em>Anything</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getDefaultMethods()
 * @model
 * @generated
 */
public interface DefaultMethods extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getDefaultMethods_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.DefaultMethods#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Anything</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Anything</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anything</em>' containment reference.
   * @see #setAnything(Anything)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getDefaultMethods_Anything()
   * @model containment="true"
   * @generated
   */
  Anything getAnything();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.DefaultMethods#getAnything <em>Anything</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Anything</em>' containment reference.
   * @see #getAnything()
   * @generated
   */
  void setAnything(Anything value);

} // DefaultMethods
