/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.Event#getEventattributes <em>Eventattributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends KindOfEvent
{
  /**
   * Returns the value of the '<em><b>Eventattributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Eventattributes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eventattributes</em>' containment reference.
   * @see #setEventattributes(Attributes)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getEvent_Eventattributes()
   * @model containment="true"
   * @generated
   */
  Attributes getEventattributes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.Event#getEventattributes <em>Eventattributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eventattributes</em>' containment reference.
   * @see #getEventattributes()
   * @generated
   */
  void setEventattributes(Attributes value);

} // Event
