/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extra Parenthesis Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getExtraParenthesisRule()
 * @model
 * @generated
 */
public interface ExtraParenthesisRule extends EObject
{
} // ExtraParenthesisRule
