/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Join Follow By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.JoinFollowBy#getFollowsByJoinList <em>Follows By Join List</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.JoinFollowBy#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getJoinFollowBy()
 * @model
 * @generated
 */
public interface JoinFollowBy extends EObject
{
  /**
   * Returns the value of the '<em><b>Follows By Join List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.AbstractFollowBy}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Follows By Join List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Follows By Join List</em>' containment reference list.
   * @see org.xtext.example.mydsl.esper.EsperPackage#getJoinFollowBy_FollowsByJoinList()
   * @model containment="true"
   * @generated
   */
  EList<AbstractFollowBy> getFollowsByJoinList();

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.Operators}.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.esper.Operators}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute list.
   * @see org.xtext.example.mydsl.esper.Operators
   * @see org.xtext.example.mydsl.esper.EsperPackage#getJoinFollowBy_Operator()
   * @model unique="false"
   * @generated
   */
  EList<Operators> getOperator();

} // JoinFollowBy
