/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.Pattern#getJoinFollowBy <em>Join Follow By</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.Pattern#getWin <em>Win</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getPattern()
 * @model
 * @generated
 */
public interface Pattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Join Follow By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Join Follow By</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Join Follow By</em>' containment reference.
   * @see #setJoinFollowBy(JoinFollowBy)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getPattern_JoinFollowBy()
   * @model containment="true"
   * @generated
   */
  JoinFollowBy getJoinFollowBy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.Pattern#getJoinFollowBy <em>Join Follow By</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Join Follow By</em>' containment reference.
   * @see #getJoinFollowBy()
   * @generated
   */
  void setJoinFollowBy(JoinFollowBy value);

  /**
   * Returns the value of the '<em><b>Win</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Win</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Win</em>' containment reference.
   * @see #setWin(Win)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getPattern_Win()
   * @model containment="true"
   * @generated
   */
  Win getWin();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.Pattern#getWin <em>Win</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Win</em>' containment reference.
   * @see #getWin()
   * @generated
   */
  void setWin(Win value);

} // Pattern
