/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Priority</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.Priority#getPriorityInt <em>Priority Int</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getPriority()
 * @model
 * @generated
 */
public interface Priority extends EObject
{
  /**
   * Returns the value of the '<em><b>Priority Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Priority Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority Int</em>' attribute.
   * @see #setPriorityInt(int)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getPriority_PriorityInt()
   * @model
   * @generated
   */
  int getPriorityInt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.Priority#getPriorityInt <em>Priority Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority Int</em>' attribute.
   * @see #getPriorityInt()
   * @generated
   */
  void setPriorityInt(int value);

} // Priority
