/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Parts</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getNameRule <em>Name Rule</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getInsert <em>Insert</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getSelectRule <em>Select Rule</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getFromRule <em>From Rule</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getGroupBy <em>Group By</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.RuleParts#getHaving <em>Having</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts()
 * @model
 * @generated
 */
public interface RuleParts extends EObject
{
  /**
   * Returns the value of the '<em><b>Name Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Rule</em>' containment reference.
   * @see #setNameRule(Name)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_NameRule()
   * @model containment="true"
   * @generated
   */
  Name getNameRule();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getNameRule <em>Name Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Rule</em>' containment reference.
   * @see #getNameRule()
   * @generated
   */
  void setNameRule(Name value);

  /**
   * Returns the value of the '<em><b>Insert</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Insert</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insert</em>' containment reference.
   * @see #setInsert(Insert)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_Insert()
   * @model containment="true"
   * @generated
   */
  Insert getInsert();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getInsert <em>Insert</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Insert</em>' containment reference.
   * @see #getInsert()
   * @generated
   */
  void setInsert(Insert value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Priority</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' containment reference.
   * @see #setPriority(Priority)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_Priority()
   * @model containment="true"
   * @generated
   */
  Priority getPriority();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getPriority <em>Priority</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' containment reference.
   * @see #getPriority()
   * @generated
   */
  void setPriority(Priority value);

  /**
   * Returns the value of the '<em><b>Select Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Select Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Select Rule</em>' containment reference.
   * @see #setSelectRule(Select)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_SelectRule()
   * @model containment="true"
   * @generated
   */
  Select getSelectRule();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getSelectRule <em>Select Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Select Rule</em>' containment reference.
   * @see #getSelectRule()
   * @generated
   */
  void setSelectRule(Select value);

  /**
   * Returns the value of the '<em><b>From Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Rule</em>' containment reference.
   * @see #setFromRule(From)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_FromRule()
   * @model containment="true"
   * @generated
   */
  From getFromRule();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getFromRule <em>From Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Rule</em>' containment reference.
   * @see #getFromRule()
   * @generated
   */
  void setFromRule(From value);

  /**
   * Returns the value of the '<em><b>Group By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Group By</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group By</em>' containment reference.
   * @see #setGroupBy(GroupBy)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_GroupBy()
   * @model containment="true"
   * @generated
   */
  GroupBy getGroupBy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getGroupBy <em>Group By</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group By</em>' containment reference.
   * @see #getGroupBy()
   * @generated
   */
  void setGroupBy(GroupBy value);

  /**
   * Returns the value of the '<em><b>Having</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Having</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Having</em>' containment reference.
   * @see #setHaving(Having)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getRuleParts_Having()
   * @model containment="true"
   * @generated
   */
  Having getHaving();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.RuleParts#getHaving <em>Having</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Having</em>' containment reference.
   * @see #getHaving()
   * @generated
   */
  void setHaving(Having value);

} // RuleParts
