/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.Select#getSelectAttributes <em>Select Attributes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.Select#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.Select#isAsterisk <em>Asterisk</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends EObject
{
  /**
   * Returns the value of the '<em><b>Select Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.SelectAttributesDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Select Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Select Attributes</em>' containment reference list.
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelect_SelectAttributes()
   * @model containment="true"
   * @generated
   */
  EList<SelectAttributesDefinition> getSelectAttributes();

  /**
   * Returns the value of the '<em><b>Alias</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alias</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' attribute list.
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelect_Alias()
   * @model unique="false"
   * @generated
   */
  EList<String> getAlias();

  /**
   * Returns the value of the '<em><b>Asterisk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Asterisk</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asterisk</em>' attribute.
   * @see #setAsterisk(boolean)
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelect_Asterisk()
   * @model
   * @generated
   */
  boolean isAsterisk();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.esper.Select#isAsterisk <em>Asterisk</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asterisk</em>' attribute.
   * @see #isAsterisk()
   * @generated
   */
  void setAsterisk(boolean value);

} // Select
