/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Attributes Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.SelectAttributesDefinition#getRightSide <em>Right Side</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.SelectAttributesDefinition#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.SelectAttributesDefinition#getLeftSide <em>Left Side</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.esper.EsperPackage#getSelectAttributesDefinition()
 * @model
 * @generated
 */
public interface SelectAttributesDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Right Side</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.KindSelectAttributesDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right Side</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Side</em>' containment reference list.
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelectAttributesDefinition_RightSide()
   * @model containment="true"
   * @generated
   */
  EList<KindSelectAttributesDefinition> getRightSide();

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.Operators}.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.esper.Operators}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute list.
   * @see org.xtext.example.mydsl.esper.Operators
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelectAttributesDefinition_Operator()
   * @model unique="false"
   * @generated
   */
  EList<Operators> getOperator();

  /**
   * Returns the value of the '<em><b>Left Side</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.esper.KindSelectAttributesDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left Side</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Side</em>' containment reference list.
   * @see org.xtext.example.mydsl.esper.EsperPackage#getSelectAttributesDefinition_LeftSide()
   * @model containment="true"
   * @generated
   */
  EList<KindSelectAttributesDefinition> getLeftSide();

} // SelectAttributesDefinition
