/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractEsperIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EsperIdeModule extends AbstractEsperIdeModule {
}
