/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.esper.Anything;
import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.ExtraParenthesisRule;
import org.xtext.example.mydsl.esper.Operators;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Anything</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.AnythingImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.AnythingImpl#getExtraParenthesis <em>Extra Parenthesis</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AnythingImpl extends ExtraParenthesisRuleImpl implements Anything
{
  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected EList<Operators> operator;

  /**
   * The cached value of the '{@link #getExtraParenthesis() <em>Extra Parenthesis</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExtraParenthesis()
   * @generated
   * @ordered
   */
  protected EList<ExtraParenthesisRule> extraParenthesis;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnythingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.ANYTHING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Operators> getOperator()
  {
    if (operator == null)
    {
      operator = new EDataTypeEList<Operators>(Operators.class, this, EsperPackage.ANYTHING__OPERATOR);
    }
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ExtraParenthesisRule> getExtraParenthesis()
  {
    if (extraParenthesis == null)
    {
      extraParenthesis = new EObjectContainmentEList<ExtraParenthesisRule>(ExtraParenthesisRule.class, this, EsperPackage.ANYTHING__EXTRA_PARENTHESIS);
    }
    return extraParenthesis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsperPackage.ANYTHING__EXTRA_PARENTHESIS:
        return ((InternalEList<?>)getExtraParenthesis()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsperPackage.ANYTHING__OPERATOR:
        return getOperator();
      case EsperPackage.ANYTHING__EXTRA_PARENTHESIS:
        return getExtraParenthesis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsperPackage.ANYTHING__OPERATOR:
        getOperator().clear();
        getOperator().addAll((Collection<? extends Operators>)newValue);
        return;
      case EsperPackage.ANYTHING__EXTRA_PARENTHESIS:
        getExtraParenthesis().clear();
        getExtraParenthesis().addAll((Collection<? extends ExtraParenthesisRule>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.ANYTHING__OPERATOR:
        getOperator().clear();
        return;
      case EsperPackage.ANYTHING__EXTRA_PARENTHESIS:
        getExtraParenthesis().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.ANYTHING__OPERATOR:
        return operator != null && !operator.isEmpty();
      case EsperPackage.ANYTHING__EXTRA_PARENTHESIS:
        return extraParenthesis != null && !extraParenthesis.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(')');
    return result.toString();
  }

} //AnythingImpl
