/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.esper.AbstractFollowBy;
import org.xtext.example.mydsl.esper.Anything;
import org.xtext.example.mydsl.esper.Attributes;
import org.xtext.example.mydsl.esper.AttributesDefinition;
import org.xtext.example.mydsl.esper.DefaultMethods;
import org.xtext.example.mydsl.esper.Domainmodel;
import org.xtext.example.mydsl.esper.EsperFactory;
import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.Event;
import org.xtext.example.mydsl.esper.ExtraParenthesisRule;
import org.xtext.example.mydsl.esper.FollowBy;
import org.xtext.example.mydsl.esper.FollowByWhere;
import org.xtext.example.mydsl.esper.From;
import org.xtext.example.mydsl.esper.GroupBy;
import org.xtext.example.mydsl.esper.Having;
import org.xtext.example.mydsl.esper.Insert;
import org.xtext.example.mydsl.esper.JoinFollowBy;
import org.xtext.example.mydsl.esper.KindOfEvent;
import org.xtext.example.mydsl.esper.KindSelectAttributesDefinition;
import org.xtext.example.mydsl.esper.Name;
import org.xtext.example.mydsl.esper.Operators;
import org.xtext.example.mydsl.esper.Pattern;
import org.xtext.example.mydsl.esper.Priority;
import org.xtext.example.mydsl.esper.RuleParts;
import org.xtext.example.mydsl.esper.Select;
import org.xtext.example.mydsl.esper.SelectAttributesDefinition;
import org.xtext.example.mydsl.esper.SingleDefinition;
import org.xtext.example.mydsl.esper.SingleSelectDefinition;
import org.xtext.example.mydsl.esper.TerminalExpression;
import org.xtext.example.mydsl.esper.Timer;
import org.xtext.example.mydsl.esper.Win;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EsperPackageImpl extends EPackageImpl implements EsperPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass domainmodelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass attributesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass attributesDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rulePartsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass insertEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass priorityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass selectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kindSelectAttributesDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass selectAttributesDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleSelectDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fromEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass joinFollowByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass abstractFollowByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass followByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminalExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kindOfEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass winEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass followByWhereEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass groupByEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass havingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defaultMethodsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass anythingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass extraParenthesisRuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum operatorsEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.esper.EsperPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private EsperPackageImpl()
  {
    super(eNS_URI, EsperFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link EsperPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static EsperPackage init()
  {
    if (isInited) return (EsperPackage)EPackage.Registry.INSTANCE.getEPackage(EsperPackage.eNS_URI);

    // Obtain or create and register package
    EsperPackageImpl theEsperPackage = (EsperPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof EsperPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new EsperPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theEsperPackage.createPackageContents();

    // Initialize created meta-data
    theEsperPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theEsperPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(EsperPackage.eNS_URI, theEsperPackage);
    return theEsperPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDomainmodel()
  {
    return domainmodelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDomainmodel_Rules()
  {
    return (EReference)domainmodelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDomainmodel_Events()
  {
    return (EReference)domainmodelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEvent()
  {
    return eventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEvent_Eventattributes()
  {
    return (EReference)eventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAttributes()
  {
    return attributesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAttributes_Attribute()
  {
    return (EReference)attributesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAttributesDefinition()
  {
    return attributesDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAttributesDefinition_Name()
  {
    return (EAttribute)attributesDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAttributesDefinition_Type()
  {
    return (EAttribute)attributesDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRuleParts()
  {
    return rulePartsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_NameRule()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_Insert()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_Priority()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_SelectRule()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_FromRule()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_GroupBy()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleParts_Having()
  {
    return (EReference)rulePartsEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInsert()
  {
    return insertEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getName_()
  {
    return nameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getName_Name()
  {
    return (EAttribute)nameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPriority()
  {
    return priorityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPriority_PriorityInt()
  {
    return (EAttribute)priorityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSelect()
  {
    return selectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSelect_SelectAttributes()
  {
    return (EReference)selectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSelect_Alias()
  {
    return (EAttribute)selectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSelect_Asterisk()
  {
    return (EAttribute)selectEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKindSelectAttributesDefinition()
  {
    return kindSelectAttributesDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getKindSelectAttributesDefinition_SingleSelectDefinition()
  {
    return (EReference)kindSelectAttributesDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getKindSelectAttributesDefinition_DefaultMethod()
  {
    return (EReference)kindSelectAttributesDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getKindSelectAttributesDefinition_Int()
  {
    return (EAttribute)kindSelectAttributesDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getKindSelectAttributesDefinition_String()
  {
    return (EAttribute)kindSelectAttributesDefinitionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSelectAttributesDefinition()
  {
    return selectAttributesDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSelectAttributesDefinition_RightSide()
  {
    return (EReference)selectAttributesDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSelectAttributesDefinition_Operator()
  {
    return (EAttribute)selectAttributesDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSelectAttributesDefinition_LeftSide()
  {
    return (EReference)selectAttributesDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleSelectDefinition()
  {
    return singleSelectDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSingleSelectDefinition_Event()
  {
    return (EReference)singleSelectDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSingleSelectDefinition_Attribute()
  {
    return (EAttribute)singleSelectDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFrom()
  {
    return fromEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFrom_Event()
  {
    return (EReference)fromEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFrom_Anything()
  {
    return (EReference)fromEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFrom_Pattern()
  {
    return (EReference)fromEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPattern()
  {
    return patternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPattern_JoinFollowBy()
  {
    return (EReference)patternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPattern_Win()
  {
    return (EReference)patternEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getJoinFollowBy()
  {
    return joinFollowByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getJoinFollowBy_FollowsByJoinList()
  {
    return (EReference)joinFollowByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getJoinFollowBy_Operator()
  {
    return (EAttribute)joinFollowByEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAbstractFollowBy()
  {
    return abstractFollowByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAbstractFollowBy_FollowBy()
  {
    return (EReference)abstractFollowByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAbstractFollowBy_WherePart()
  {
    return (EReference)abstractFollowByEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFollowBy()
  {
    return followByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFollowBy_LeftSide()
  {
    return (EReference)followByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFollowBy_RightSide()
  {
    return (EReference)followByEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTerminalExpression()
  {
    return terminalExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTerminalExpression_Every()
  {
    return (EAttribute)terminalExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTerminalExpression_EveryExpression()
  {
    return (EReference)terminalExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTerminalExpression_Parenthesis()
  {
    return (EAttribute)terminalExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTerminalExpression_BetweenParenthesis()
  {
    return (EReference)terminalExpressionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTerminalExpression_SingleDefinition()
  {
    return (EReference)terminalExpressionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKindOfEvent()
  {
    return kindOfEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getKindOfEvent_Name()
  {
    return (EAttribute)kindOfEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleDefinition()
  {
    return singleDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSingleDefinition_Name()
  {
    return (EAttribute)singleDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSingleDefinition_SimpleEvents()
  {
    return (EReference)singleDefinitionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSingleDefinition_Anything()
  {
    return (EReference)singleDefinitionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWin()
  {
    return winEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWin_DefaultMethod()
  {
    return (EReference)winEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFollowByWhere()
  {
    return followByWhereEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFollowByWhere_Timer()
  {
    return (EReference)followByWhereEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTimer()
  {
    return timerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTimer_DefaultMethod()
  {
    return (EReference)timerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGroupBy()
  {
    return groupByEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGroupBy_Anything()
  {
    return (EReference)groupByEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHaving()
  {
    return havingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHaving_DefaultMethod()
  {
    return (EReference)havingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHaving_Operator()
  {
    return (EAttribute)havingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHaving_Anything()
  {
    return (EReference)havingEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDefaultMethods()
  {
    return defaultMethodsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDefaultMethods_Name()
  {
    return (EAttribute)defaultMethodsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDefaultMethods_Anything()
  {
    return (EReference)defaultMethodsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAnything()
  {
    return anythingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAnything_Operator()
  {
    return (EAttribute)anythingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAnything_ExtraParenthesis()
  {
    return (EReference)anythingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExtraParenthesisRule()
  {
    return extraParenthesisRuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getOperators()
  {
    return operatorsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EsperFactory getEsperFactory()
  {
    return (EsperFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    domainmodelEClass = createEClass(DOMAINMODEL);
    createEReference(domainmodelEClass, DOMAINMODEL__RULES);
    createEReference(domainmodelEClass, DOMAINMODEL__EVENTS);

    eventEClass = createEClass(EVENT);
    createEReference(eventEClass, EVENT__EVENTATTRIBUTES);

    attributesEClass = createEClass(ATTRIBUTES);
    createEReference(attributesEClass, ATTRIBUTES__ATTRIBUTE);

    attributesDefinitionEClass = createEClass(ATTRIBUTES_DEFINITION);
    createEAttribute(attributesDefinitionEClass, ATTRIBUTES_DEFINITION__NAME);
    createEAttribute(attributesDefinitionEClass, ATTRIBUTES_DEFINITION__TYPE);

    rulePartsEClass = createEClass(RULE_PARTS);
    createEReference(rulePartsEClass, RULE_PARTS__NAME_RULE);
    createEReference(rulePartsEClass, RULE_PARTS__INSERT);
    createEReference(rulePartsEClass, RULE_PARTS__PRIORITY);
    createEReference(rulePartsEClass, RULE_PARTS__SELECT_RULE);
    createEReference(rulePartsEClass, RULE_PARTS__FROM_RULE);
    createEReference(rulePartsEClass, RULE_PARTS__GROUP_BY);
    createEReference(rulePartsEClass, RULE_PARTS__HAVING);

    insertEClass = createEClass(INSERT);

    nameEClass = createEClass(NAME);
    createEAttribute(nameEClass, NAME__NAME);

    priorityEClass = createEClass(PRIORITY);
    createEAttribute(priorityEClass, PRIORITY__PRIORITY_INT);

    selectEClass = createEClass(SELECT);
    createEReference(selectEClass, SELECT__SELECT_ATTRIBUTES);
    createEAttribute(selectEClass, SELECT__ALIAS);
    createEAttribute(selectEClass, SELECT__ASTERISK);

    kindSelectAttributesDefinitionEClass = createEClass(KIND_SELECT_ATTRIBUTES_DEFINITION);
    createEReference(kindSelectAttributesDefinitionEClass, KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION);
    createEReference(kindSelectAttributesDefinitionEClass, KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD);
    createEAttribute(kindSelectAttributesDefinitionEClass, KIND_SELECT_ATTRIBUTES_DEFINITION__INT);
    createEAttribute(kindSelectAttributesDefinitionEClass, KIND_SELECT_ATTRIBUTES_DEFINITION__STRING);

    selectAttributesDefinitionEClass = createEClass(SELECT_ATTRIBUTES_DEFINITION);
    createEReference(selectAttributesDefinitionEClass, SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE);
    createEAttribute(selectAttributesDefinitionEClass, SELECT_ATTRIBUTES_DEFINITION__OPERATOR);
    createEReference(selectAttributesDefinitionEClass, SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE);

    singleSelectDefinitionEClass = createEClass(SINGLE_SELECT_DEFINITION);
    createEReference(singleSelectDefinitionEClass, SINGLE_SELECT_DEFINITION__EVENT);
    createEAttribute(singleSelectDefinitionEClass, SINGLE_SELECT_DEFINITION__ATTRIBUTE);

    fromEClass = createEClass(FROM);
    createEReference(fromEClass, FROM__EVENT);
    createEReference(fromEClass, FROM__ANYTHING);
    createEReference(fromEClass, FROM__PATTERN);

    patternEClass = createEClass(PATTERN);
    createEReference(patternEClass, PATTERN__JOIN_FOLLOW_BY);
    createEReference(patternEClass, PATTERN__WIN);

    joinFollowByEClass = createEClass(JOIN_FOLLOW_BY);
    createEReference(joinFollowByEClass, JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST);
    createEAttribute(joinFollowByEClass, JOIN_FOLLOW_BY__OPERATOR);

    abstractFollowByEClass = createEClass(ABSTRACT_FOLLOW_BY);
    createEReference(abstractFollowByEClass, ABSTRACT_FOLLOW_BY__FOLLOW_BY);
    createEReference(abstractFollowByEClass, ABSTRACT_FOLLOW_BY__WHERE_PART);

    followByEClass = createEClass(FOLLOW_BY);
    createEReference(followByEClass, FOLLOW_BY__LEFT_SIDE);
    createEReference(followByEClass, FOLLOW_BY__RIGHT_SIDE);

    terminalExpressionEClass = createEClass(TERMINAL_EXPRESSION);
    createEAttribute(terminalExpressionEClass, TERMINAL_EXPRESSION__EVERY);
    createEReference(terminalExpressionEClass, TERMINAL_EXPRESSION__EVERY_EXPRESSION);
    createEAttribute(terminalExpressionEClass, TERMINAL_EXPRESSION__PARENTHESIS);
    createEReference(terminalExpressionEClass, TERMINAL_EXPRESSION__BETWEEN_PARENTHESIS);
    createEReference(terminalExpressionEClass, TERMINAL_EXPRESSION__SINGLE_DEFINITION);

    kindOfEventEClass = createEClass(KIND_OF_EVENT);
    createEAttribute(kindOfEventEClass, KIND_OF_EVENT__NAME);

    singleDefinitionEClass = createEClass(SINGLE_DEFINITION);
    createEAttribute(singleDefinitionEClass, SINGLE_DEFINITION__NAME);
    createEReference(singleDefinitionEClass, SINGLE_DEFINITION__SIMPLE_EVENTS);
    createEReference(singleDefinitionEClass, SINGLE_DEFINITION__ANYTHING);

    winEClass = createEClass(WIN);
    createEReference(winEClass, WIN__DEFAULT_METHOD);

    followByWhereEClass = createEClass(FOLLOW_BY_WHERE);
    createEReference(followByWhereEClass, FOLLOW_BY_WHERE__TIMER);

    timerEClass = createEClass(TIMER);
    createEReference(timerEClass, TIMER__DEFAULT_METHOD);

    groupByEClass = createEClass(GROUP_BY);
    createEReference(groupByEClass, GROUP_BY__ANYTHING);

    havingEClass = createEClass(HAVING);
    createEReference(havingEClass, HAVING__DEFAULT_METHOD);
    createEAttribute(havingEClass, HAVING__OPERATOR);
    createEReference(havingEClass, HAVING__ANYTHING);

    defaultMethodsEClass = createEClass(DEFAULT_METHODS);
    createEAttribute(defaultMethodsEClass, DEFAULT_METHODS__NAME);
    createEReference(defaultMethodsEClass, DEFAULT_METHODS__ANYTHING);

    anythingEClass = createEClass(ANYTHING);
    createEAttribute(anythingEClass, ANYTHING__OPERATOR);
    createEReference(anythingEClass, ANYTHING__EXTRA_PARENTHESIS);

    extraParenthesisRuleEClass = createEClass(EXTRA_PARENTHESIS_RULE);

    // Create enums
    operatorsEEnum = createEEnum(OPERATORS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    eventEClass.getESuperTypes().add(this.getKindOfEvent());
    insertEClass.getESuperTypes().add(this.getKindOfEvent());
    anythingEClass.getESuperTypes().add(this.getExtraParenthesisRule());

    // Initialize classes and features; add operations and parameters
    initEClass(domainmodelEClass, Domainmodel.class, "Domainmodel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDomainmodel_Rules(), this.getRuleParts(), null, "rules", null, 0, -1, Domainmodel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDomainmodel_Events(), this.getEvent(), null, "events", null, 0, -1, Domainmodel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eventEClass, Event.class, "Event", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEvent_Eventattributes(), this.getAttributes(), null, "eventattributes", null, 0, 1, Event.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(attributesEClass, Attributes.class, "Attributes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAttributes_Attribute(), this.getAttributesDefinition(), null, "attribute", null, 0, -1, Attributes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(attributesDefinitionEClass, AttributesDefinition.class, "AttributesDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAttributesDefinition_Name(), ecorePackage.getEString(), "name", null, 0, -1, AttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAttributesDefinition_Type(), ecorePackage.getEString(), "type", null, 0, -1, AttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rulePartsEClass, RuleParts.class, "RuleParts", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRuleParts_NameRule(), this.getName_(), null, "nameRule", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_Insert(), this.getInsert(), null, "insert", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_Priority(), this.getPriority(), null, "priority", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_SelectRule(), this.getSelect(), null, "selectRule", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_FromRule(), this.getFrom(), null, "fromRule", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_GroupBy(), this.getGroupBy(), null, "groupBy", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleParts_Having(), this.getHaving(), null, "having", null, 0, 1, RuleParts.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(insertEClass, Insert.class, "Insert", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(nameEClass, Name.class, "Name", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getName_Name(), ecorePackage.getEString(), "name", null, 0, 1, Name.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(priorityEClass, Priority.class, "Priority", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPriority_PriorityInt(), ecorePackage.getEInt(), "priorityInt", null, 0, 1, Priority.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(selectEClass, Select.class, "Select", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSelect_SelectAttributes(), this.getSelectAttributesDefinition(), null, "selectAttributes", null, 0, -1, Select.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelect_Alias(), ecorePackage.getEString(), "alias", null, 0, -1, Select.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelect_Asterisk(), ecorePackage.getEBoolean(), "asterisk", null, 0, 1, Select.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(kindSelectAttributesDefinitionEClass, KindSelectAttributesDefinition.class, "KindSelectAttributesDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getKindSelectAttributesDefinition_SingleSelectDefinition(), this.getSingleSelectDefinition(), null, "singleSelectDefinition", null, 0, 1, KindSelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getKindSelectAttributesDefinition_DefaultMethod(), this.getDefaultMethods(), null, "defaultMethod", null, 0, 1, KindSelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getKindSelectAttributesDefinition_Int(), ecorePackage.getEInt(), "int", null, 0, 1, KindSelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getKindSelectAttributesDefinition_String(), ecorePackage.getEString(), "string", null, 0, 1, KindSelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(selectAttributesDefinitionEClass, SelectAttributesDefinition.class, "SelectAttributesDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSelectAttributesDefinition_RightSide(), this.getKindSelectAttributesDefinition(), null, "rightSide", null, 0, -1, SelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelectAttributesDefinition_Operator(), this.getOperators(), "operator", null, 0, -1, SelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSelectAttributesDefinition_LeftSide(), this.getKindSelectAttributesDefinition(), null, "leftSide", null, 0, -1, SelectAttributesDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleSelectDefinitionEClass, SingleSelectDefinition.class, "SingleSelectDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSingleSelectDefinition_Event(), this.getSingleDefinition(), null, "event", null, 0, -1, SingleSelectDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSingleSelectDefinition_Attribute(), ecorePackage.getEString(), "attribute", null, 0, -1, SingleSelectDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fromEClass, From.class, "From", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFrom_Event(), this.getEvent(), null, "event", null, 0, 1, From.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFrom_Anything(), this.getAnything(), null, "anything", null, 0, 1, From.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFrom_Pattern(), this.getPattern(), null, "pattern", null, 0, 1, From.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternEClass, Pattern.class, "Pattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPattern_JoinFollowBy(), this.getJoinFollowBy(), null, "joinFollowBy", null, 0, 1, Pattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPattern_Win(), this.getWin(), null, "win", null, 0, 1, Pattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(joinFollowByEClass, JoinFollowBy.class, "JoinFollowBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJoinFollowBy_FollowsByJoinList(), this.getAbstractFollowBy(), null, "followsByJoinList", null, 0, -1, JoinFollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getJoinFollowBy_Operator(), this.getOperators(), "operator", null, 0, -1, JoinFollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(abstractFollowByEClass, AbstractFollowBy.class, "AbstractFollowBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAbstractFollowBy_FollowBy(), this.getFollowBy(), null, "followBy", null, 0, 1, AbstractFollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAbstractFollowBy_WherePart(), this.getFollowByWhere(), null, "wherePart", null, 0, 1, AbstractFollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(followByEClass, FollowBy.class, "FollowBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFollowBy_LeftSide(), this.getTerminalExpression(), null, "leftSide", null, 0, 1, FollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFollowBy_RightSide(), this.getTerminalExpression(), null, "rightSide", null, 0, -1, FollowBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(terminalExpressionEClass, TerminalExpression.class, "TerminalExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTerminalExpression_Every(), ecorePackage.getEBoolean(), "every", null, 0, 1, TerminalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTerminalExpression_EveryExpression(), this.getFollowBy(), null, "everyExpression", null, 0, 1, TerminalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTerminalExpression_Parenthesis(), ecorePackage.getEBoolean(), "parenthesis", null, 0, 1, TerminalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTerminalExpression_BetweenParenthesis(), this.getFollowBy(), null, "betweenParenthesis", null, 0, 1, TerminalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTerminalExpression_SingleDefinition(), this.getSingleDefinition(), null, "singleDefinition", null, 0, 1, TerminalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(kindOfEventEClass, KindOfEvent.class, "KindOfEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKindOfEvent_Name(), ecorePackage.getEString(), "name", null, 0, 1, KindOfEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleDefinitionEClass, SingleDefinition.class, "SingleDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSingleDefinition_Name(), ecorePackage.getEString(), "name", null, 0, 1, SingleDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSingleDefinition_SimpleEvents(), this.getKindOfEvent(), null, "simpleEvents", null, 0, 1, SingleDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSingleDefinition_Anything(), this.getAnything(), null, "anything", null, 0, 1, SingleDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(winEClass, Win.class, "Win", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWin_DefaultMethod(), this.getDefaultMethods(), null, "defaultMethod", null, 0, 1, Win.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(followByWhereEClass, FollowByWhere.class, "FollowByWhere", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFollowByWhere_Timer(), this.getTimer(), null, "timer", null, 0, 1, FollowByWhere.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timerEClass, Timer.class, "Timer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTimer_DefaultMethod(), this.getDefaultMethods(), null, "defaultMethod", null, 0, 1, Timer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(groupByEClass, GroupBy.class, "GroupBy", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGroupBy_Anything(), this.getAnything(), null, "anything", null, 0, 1, GroupBy.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(havingEClass, Having.class, "Having", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHaving_DefaultMethod(), this.getDefaultMethods(), null, "defaultMethod", null, 0, 1, Having.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHaving_Operator(), this.getOperators(), "operator", null, 0, 1, Having.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getHaving_Anything(), this.getAnything(), null, "anything", null, 0, 1, Having.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defaultMethodsEClass, DefaultMethods.class, "DefaultMethods", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefaultMethods_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefaultMethods.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefaultMethods_Anything(), this.getAnything(), null, "anything", null, 0, 1, DefaultMethods.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(anythingEClass, Anything.class, "Anything", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAnything_Operator(), this.getOperators(), "operator", null, 0, -1, Anything.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAnything_ExtraParenthesis(), this.getExtraParenthesisRule(), null, "extraParenthesis", null, 0, -1, Anything.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(extraParenthesisRuleEClass, ExtraParenthesisRule.class, "ExtraParenthesisRule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Initialize enums and add enum literals
    initEEnum(operatorsEEnum, Operators.class, "Operators");
    addEEnumLiteral(operatorsEEnum, Operators.EQUAL);
    addEEnumLiteral(operatorsEEnum, Operators.LESS_THAN);
    addEEnumLiteral(operatorsEEnum, Operators.MORE_THAN);
    addEEnumLiteral(operatorsEEnum, Operators.LESS_EQUAL_THAN);
    addEEnumLiteral(operatorsEEnum, Operators.MORE_EQUAL_THAN);
    addEEnumLiteral(operatorsEEnum, Operators.AND);
    addEEnumLiteral(operatorsEEnum, Operators.OR);
    addEEnumLiteral(operatorsEEnum, Operators.BETWEEN);
    addEEnumLiteral(operatorsEEnum, Operators.IN);
    addEEnumLiteral(operatorsEEnum, Operators.NOT);
    addEEnumLiteral(operatorsEEnum, Operators.NOT_IN);
    addEEnumLiteral(operatorsEEnum, Operators.PLUS);
    addEEnumLiteral(operatorsEEnum, Operators.MINUS);
    addEEnumLiteral(operatorsEEnum, Operators.MULTIPLICATION);
    addEEnumLiteral(operatorsEEnum, Operators.ISNOT);

    // Create resource
    createResource(eNS_URI);
  }

} //EsperPackageImpl
