/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.esper.Attributes;
import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.Event;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.EventImpl#getEventattributes <em>Eventattributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EventImpl extends KindOfEventImpl implements Event
{
  /**
   * The cached value of the '{@link #getEventattributes() <em>Eventattributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEventattributes()
   * @generated
   * @ordered
   */
  protected Attributes eventattributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attributes getEventattributes()
  {
    return eventattributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEventattributes(Attributes newEventattributes, NotificationChain msgs)
  {
    Attributes oldEventattributes = eventattributes;
    eventattributes = newEventattributes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EsperPackage.EVENT__EVENTATTRIBUTES, oldEventattributes, newEventattributes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEventattributes(Attributes newEventattributes)
  {
    if (newEventattributes != eventattributes)
    {
      NotificationChain msgs = null;
      if (eventattributes != null)
        msgs = ((InternalEObject)eventattributes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EsperPackage.EVENT__EVENTATTRIBUTES, null, msgs);
      if (newEventattributes != null)
        msgs = ((InternalEObject)newEventattributes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EsperPackage.EVENT__EVENTATTRIBUTES, null, msgs);
      msgs = basicSetEventattributes(newEventattributes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsperPackage.EVENT__EVENTATTRIBUTES, newEventattributes, newEventattributes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsperPackage.EVENT__EVENTATTRIBUTES:
        return basicSetEventattributes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsperPackage.EVENT__EVENTATTRIBUTES:
        return getEventattributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsperPackage.EVENT__EVENTATTRIBUTES:
        setEventattributes((Attributes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.EVENT__EVENTATTRIBUTES:
        setEventattributes((Attributes)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.EVENT__EVENTATTRIBUTES:
        return eventattributes != null;
    }
    return super.eIsSet(featureID);
  }

} //EventImpl
