/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.ExtraParenthesisRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Extra Parenthesis Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExtraParenthesisRuleImpl extends MinimalEObjectImpl.Container implements ExtraParenthesisRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExtraParenthesisRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.EXTRA_PARENTHESIS_RULE;
  }

} //ExtraParenthesisRuleImpl
