/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.esper.AbstractFollowBy;
import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.JoinFollowBy;
import org.xtext.example.mydsl.esper.Operators;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Join Follow By</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.JoinFollowByImpl#getFollowsByJoinList <em>Follows By Join List</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.JoinFollowByImpl#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JoinFollowByImpl extends MinimalEObjectImpl.Container implements JoinFollowBy
{
  /**
   * The cached value of the '{@link #getFollowsByJoinList() <em>Follows By Join List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFollowsByJoinList()
   * @generated
   * @ordered
   */
  protected EList<AbstractFollowBy> followsByJoinList;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected EList<Operators> operator;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JoinFollowByImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.JOIN_FOLLOW_BY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AbstractFollowBy> getFollowsByJoinList()
  {
    if (followsByJoinList == null)
    {
      followsByJoinList = new EObjectContainmentEList<AbstractFollowBy>(AbstractFollowBy.class, this, EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST);
    }
    return followsByJoinList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Operators> getOperator()
  {
    if (operator == null)
    {
      operator = new EDataTypeEList<Operators>(Operators.class, this, EsperPackage.JOIN_FOLLOW_BY__OPERATOR);
    }
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST:
        return ((InternalEList<?>)getFollowsByJoinList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST:
        return getFollowsByJoinList();
      case EsperPackage.JOIN_FOLLOW_BY__OPERATOR:
        return getOperator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST:
        getFollowsByJoinList().clear();
        getFollowsByJoinList().addAll((Collection<? extends AbstractFollowBy>)newValue);
        return;
      case EsperPackage.JOIN_FOLLOW_BY__OPERATOR:
        getOperator().clear();
        getOperator().addAll((Collection<? extends Operators>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST:
        getFollowsByJoinList().clear();
        return;
      case EsperPackage.JOIN_FOLLOW_BY__OPERATOR:
        getOperator().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.JOIN_FOLLOW_BY__FOLLOWS_BY_JOIN_LIST:
        return followsByJoinList != null && !followsByJoinList.isEmpty();
      case EsperPackage.JOIN_FOLLOW_BY__OPERATOR:
        return operator != null && !operator.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(')');
    return result.toString();
  }

} //JoinFollowByImpl
