/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.esper.DefaultMethods;
import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.KindSelectAttributesDefinition;
import org.xtext.example.mydsl.esper.SingleSelectDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Kind Select Attributes Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.KindSelectAttributesDefinitionImpl#getSingleSelectDefinition <em>Single Select Definition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.KindSelectAttributesDefinitionImpl#getDefaultMethod <em>Default Method</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.KindSelectAttributesDefinitionImpl#getInt <em>Int</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.KindSelectAttributesDefinitionImpl#getString <em>String</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KindSelectAttributesDefinitionImpl extends MinimalEObjectImpl.Container implements KindSelectAttributesDefinition
{
  /**
   * The cached value of the '{@link #getSingleSelectDefinition() <em>Single Select Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSingleSelectDefinition()
   * @generated
   * @ordered
   */
  protected SingleSelectDefinition singleSelectDefinition;

  /**
   * The cached value of the '{@link #getDefaultMethod() <em>Default Method</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultMethod()
   * @generated
   * @ordered
   */
  protected DefaultMethods defaultMethod;

  /**
   * The default value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected static final int INT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInt() <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt()
   * @generated
   * @ordered
   */
  protected int int_ = INT_EDEFAULT;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KindSelectAttributesDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.KIND_SELECT_ATTRIBUTES_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleSelectDefinition getSingleSelectDefinition()
  {
    return singleSelectDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSingleSelectDefinition(SingleSelectDefinition newSingleSelectDefinition, NotificationChain msgs)
  {
    SingleSelectDefinition oldSingleSelectDefinition = singleSelectDefinition;
    singleSelectDefinition = newSingleSelectDefinition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION, oldSingleSelectDefinition, newSingleSelectDefinition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSingleSelectDefinition(SingleSelectDefinition newSingleSelectDefinition)
  {
    if (newSingleSelectDefinition != singleSelectDefinition)
    {
      NotificationChain msgs = null;
      if (singleSelectDefinition != null)
        msgs = ((InternalEObject)singleSelectDefinition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION, null, msgs);
      if (newSingleSelectDefinition != null)
        msgs = ((InternalEObject)newSingleSelectDefinition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION, null, msgs);
      msgs = basicSetSingleSelectDefinition(newSingleSelectDefinition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION, newSingleSelectDefinition, newSingleSelectDefinition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefaultMethods getDefaultMethod()
  {
    return defaultMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefaultMethod(DefaultMethods newDefaultMethod, NotificationChain msgs)
  {
    DefaultMethods oldDefaultMethod = defaultMethod;
    defaultMethod = newDefaultMethod;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD, oldDefaultMethod, newDefaultMethod);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDefaultMethod(DefaultMethods newDefaultMethod)
  {
    if (newDefaultMethod != defaultMethod)
    {
      NotificationChain msgs = null;
      if (defaultMethod != null)
        msgs = ((InternalEObject)defaultMethod).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD, null, msgs);
      if (newDefaultMethod != null)
        msgs = ((InternalEObject)newDefaultMethod).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD, null, msgs);
      msgs = basicSetDefaultMethod(newDefaultMethod, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD, newDefaultMethod, newDefaultMethod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getInt()
  {
    return int_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInt(int newInt)
  {
    int oldInt = int_;
    int_ = newInt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__INT, oldInt, int_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION:
        return basicSetSingleSelectDefinition(null, msgs);
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD:
        return basicSetDefaultMethod(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION:
        return getSingleSelectDefinition();
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD:
        return getDefaultMethod();
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__INT:
        return getInt();
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__STRING:
        return getString();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION:
        setSingleSelectDefinition((SingleSelectDefinition)newValue);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD:
        setDefaultMethod((DefaultMethods)newValue);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__INT:
        setInt((Integer)newValue);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__STRING:
        setString((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION:
        setSingleSelectDefinition((SingleSelectDefinition)null);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD:
        setDefaultMethod((DefaultMethods)null);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__INT:
        setInt(INT_EDEFAULT);
        return;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__STRING:
        setString(STRING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__SINGLE_SELECT_DEFINITION:
        return singleSelectDefinition != null;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__DEFAULT_METHOD:
        return defaultMethod != null;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__INT:
        return int_ != INT_EDEFAULT;
      case EsperPackage.KIND_SELECT_ATTRIBUTES_DEFINITION__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (int: ");
    result.append(int_);
    result.append(", string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //KindSelectAttributesDefinitionImpl
