/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.esper.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.esper.EsperPackage;
import org.xtext.example.mydsl.esper.KindSelectAttributesDefinition;
import org.xtext.example.mydsl.esper.Operators;
import org.xtext.example.mydsl.esper.SelectAttributesDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Select Attributes Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.SelectAttributesDefinitionImpl#getRightSide <em>Right Side</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.SelectAttributesDefinitionImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.esper.impl.SelectAttributesDefinitionImpl#getLeftSide <em>Left Side</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SelectAttributesDefinitionImpl extends MinimalEObjectImpl.Container implements SelectAttributesDefinition
{
  /**
   * The cached value of the '{@link #getRightSide() <em>Right Side</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRightSide()
   * @generated
   * @ordered
   */
  protected EList<KindSelectAttributesDefinition> rightSide;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected EList<Operators> operator;

  /**
   * The cached value of the '{@link #getLeftSide() <em>Left Side</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeftSide()
   * @generated
   * @ordered
   */
  protected EList<KindSelectAttributesDefinition> leftSide;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelectAttributesDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EsperPackage.Literals.SELECT_ATTRIBUTES_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<KindSelectAttributesDefinition> getRightSide()
  {
    if (rightSide == null)
    {
      rightSide = new EObjectContainmentEList<KindSelectAttributesDefinition>(KindSelectAttributesDefinition.class, this, EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE);
    }
    return rightSide;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Operators> getOperator()
  {
    if (operator == null)
    {
      operator = new EDataTypeEList<Operators>(Operators.class, this, EsperPackage.SELECT_ATTRIBUTES_DEFINITION__OPERATOR);
    }
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<KindSelectAttributesDefinition> getLeftSide()
  {
    if (leftSide == null)
    {
      leftSide = new EObjectContainmentEList<KindSelectAttributesDefinition>(KindSelectAttributesDefinition.class, this, EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE);
    }
    return leftSide;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE:
        return ((InternalEList<?>)getRightSide()).basicRemove(otherEnd, msgs);
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE:
        return ((InternalEList<?>)getLeftSide()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE:
        return getRightSide();
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__OPERATOR:
        return getOperator();
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE:
        return getLeftSide();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE:
        getRightSide().clear();
        getRightSide().addAll((Collection<? extends KindSelectAttributesDefinition>)newValue);
        return;
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__OPERATOR:
        getOperator().clear();
        getOperator().addAll((Collection<? extends Operators>)newValue);
        return;
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE:
        getLeftSide().clear();
        getLeftSide().addAll((Collection<? extends KindSelectAttributesDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE:
        getRightSide().clear();
        return;
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__OPERATOR:
        getOperator().clear();
        return;
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE:
        getLeftSide().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__RIGHT_SIDE:
        return rightSide != null && !rightSide.isEmpty();
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__OPERATOR:
        return operator != null && !operator.isEmpty();
      case EsperPackage.SELECT_ATTRIBUTES_DEFINITION__LEFT_SIDE:
        return leftSide != null && !leftSide.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(')');
    return result.toString();
  }

} //SelectAttributesDefinitionImpl
