/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalEsperParser;
import org.xtext.example.mydsl.services.EsperGrammarAccess;

public class EsperParser extends AbstractAntlrParser {

	@Inject
	private EsperGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEsperParser createParser(XtextTokenStream stream) {
		return new InternalEsperParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public EsperGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EsperGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
